### ISSUE TITLE
consistency in field errors for reset-password

### ISSUE THREAD

**Issue by jonas87** [apragacz/django-rest-registration#111] opened 2020-05-29 23:10 UTC
Concerning the reset-password api:

1. if the password field contains a password that isn't long enough, response.data is an **array** with one string element stating "This password is too short. It must contain at least 8 characters."

2. if the password_confirm field doesn't match, response.data is an **object** with one key ('password_confirm') and it's value is the error message 'Passwords don't match'.

3. if the signature field is incorrect, response.data is an **object** with one key ('detail') and it's value is the error message 'Invalid signature'.

My suggestion would be for the first case that instead of an array it would also be an object with a 'password' key and the error as value. This is just as well a field error as the other 2 so it would make sense to have both the fieldname and error returned as a key value pair here instead of the array.

**Comment by apragacz** [comment] 2020-05-30 18:39
Hi @jonas87, this looks like duplicate of #110 . Could you confirm that's the case?

**Comment by jonas87** [comment] 2020-06-01 19:34
yes, my apologies, this is a duplicate

**Closed** 2020-06-02 16:45 UTC
Labels: type:feature-request
