### ISSUE TITLE
ValidationError in authentication backend breaks login view

### ISSUE THREAD

**Issue by Neraste** [apragacz/django-rest-registration#142] opened 2021-05-25 05:41 UTC
I modified my Django authentication backend to raise a `django.core.exceptions.ValidationError` if some conditions are not met for the user to allow login: if their email is not not validated (`email_validation` field instead of default `is_valid`), and if a manager didn't approve the account (`manager_validation` field). I use this exception mechanism to have a feedback on why the authentication is denied.

Now, if I try to login with a user who lacks one of the two fields, I get different behavior. Using the DRF browsable API login page, the message of the raised `ValidationError` is displayed. Using the DRR login route, the exception is not caught and the server sends a 500 error response.

Would it be possible to have the same behavior? Or the fact it works on the DRF browsable API login page is just pure luck?

Context:
- Django 2.2;
- Django REST Framework 3.11
- Django REST Registration 0.6.2

**Comment by apragacz** [comment] 2021-05-31 21:19
Hi @Neraste ,
thanks for the heads-up. That is definitely not expected here (AFAIK there is no exception handling around `auth.authenticate(...)` which could cause this). I will try to reproduce that with a test case

**Comment by apragacz** [comment] 2021-06-03 00:08
@Neraste 
I did some research and it looks that it is actually expected. According to the DRF docs:
https://www.django-rest-framework.org/api-guide/exceptions/#exception-handling-in-rest-framework-views
> REST framework's views handle various exceptions, and deal with returning appropriate error responses.
> 
> The handled exceptions are:
>
> * Subclasses of APIException raised inside REST framework.
> * Django's Http404 exception.
> * Django's PermissionDenied exception.

Which means that `django.core.exceptions.ValidationError` is not handled so it will cause HTTP 500 (which is actually happening).

Another thing is that your auth backend probably should not raise any exception as it's not on par with the API spec:
https://docs.djangoproject.com/en/dev/topics/auth/customizing/#writing-an-authentication-backend

> Either way, authenticate() should check the credentials it gets and return a user object that matches those credentials if the credentials are valid. If they’re not valid, it should return None.

The reason why the DRF browsable API login page is able to handle it is that it is actually Django `LoginView` in disguise:

https://github.com/encode/django-rest-framework/blob/410575dace9d64a53ec771ea5e21b40525ed0e95/rest_framework/urls.py#L14-L21

Considering all that, my decision would be to NOT add any additional handling for that exception, but I'm happy to be convinced otherwise.

**Comment by Neraste** [comment] 2021-06-03 11:44
It is true that Django documentation does not allow an authentication backend to raise `ValidationError` exceptions, so I know I was a bit off tracks here. I think the problem lies on the side of Django, which lacks a feedback mechanism for custom authentication models.

**Comment by Neraste** [comment] 2021-06-03 11:54
I initially posted my question on [Reddit](https://www.reddit.com/r/django/comments/njq19t/feedback_on_authentication_backend/), but it looks like no one could answer me.

**Comment by apragacz** [comment] 2021-06-04 10:53
>  I think the problem lies on the side of Django, which lacks a feedback mechanism for custom authentication models.

I believe that was a conscious design decision; validation should be done in separate step than authentication IMO. But you can reach Django maintainers about that.

> Or Django REST for not catching it?

Again I think it was done on purpose as I think it is hard to convert Django `django.core.exceptions.ValidationError` to `rest_framework.exceptions.ValidationError`(subclass of `APIException`) in a generic way. But again, you could try to talk to DRF maintainers about that.

Anyway, it looks that this issue can't be solved at DRR level, therefore I'm closing that issue.

**Closed by apragacz** 2021-06-04 10:53 UTC
Labels: type:bug
