### ISSUE TITLE
Invalid Signature When Verifying Email Address and More Using Postman

### ISSUE THREAD

**Issue by beittenc** [apragacz/django-rest-registration#86] opened 2019-10-25 16:29 UTC
### Checklist

* [X] I searched existing issues before opening this one
* [X] I reproduced the bug with the newest version

### Describe the bug
The views that require posting in a JSON body, such as verify-email, will fail with an Invalid Signature error when using Postman. This has been reported in some form in #11 and #42, but neither had a solution.

### Expected behavior
Posting into these endpoints succeeds and returns a 2XX error code as expected, like it does with cURL.

### Actual behavior
The problem appears to occur due to some temporary headers that Postman is setting. This problem has been reported with a number of APIs in other forms in https://community.getpostman.com/t/disable-temporary-headers/5271 and other tickets. After some testing, I believe it comes down to the "Accept-Encoding: gzip, deflate" header. When I include that one with cURL, I receive an error relating to binary data coming back or an invalid signature error. Excluding that single temporary header that Postman sets (which is not supported by the tool itself) allows the request to succeed.

### Steps to reproduce
1. Create a new request in Postman to POST to the verify-email endpoint with correct data
2. Send the request and receive an error

### Diagnostic info

(Please provide below contents of your Django settings.py file (after removing all sensitive information like secrets), or at least provide specific settings mentioned below)

```python
REST_REGISTRATION = {
    'REGISTER_VERIFICATION_URL': 'https://mysite.example/verify-user/',
    'RESET_PASSWORD_VERIFICATION_URL': 'https://mysite.example/reset-password/',
    'REGISTER_EMAIL_VERIFICATION_URL': 'https://mysite.example/verify-email/',

    'VERIFICATION_FROM_EMAIL': 'support@mysite.example',

    # Excluding this and using the normal id field does not change the behavior
    'USER_VERIFICATION_ID_FIELD': 'uuid',
}

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'knox.auth.TokenAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 25,
    'DEFAULT_VERSIONING_CLASS': 'rest_framework.versioning.NamespaceVersioning',
}

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'api.apps.ApiConfig',
    'knox',
    'oauth2_provider',
    'rest_framework',
    'rest_registration',
    'rolepermissions',
    'simple_history',
)
```

### Additional context

I've also requested that Postman provide a method for excluding temporary headers because of this problem (as have many other people), but I'm not sure what their release timeframe is. Hopefully this is simpler to reproduce and fix on this end.

**Comment by apragacz** [comment] 2019-10-28 10:44
@beittenc Thanks for very detailed report and doing a lot of investigative work. I wouldn't be able to figure out that this issue is Postman-related as I'm not using this application.

The fact that additional headers cause signature mismatch is certainly not ok. I still need to reproduce the issue with Postman. I will let you know about the results.

**Comment by apragacz** [comment] 2019-11-15 10:57
@beittenc Unfortunately I was unable to reproduce the issue with example api running locally (I used the [sharedlinks example](https://github.com/apragacz/django-rest-registration/tree/master/examples/sharedlinks/sharedlinks-backend) development server (`./manage.py runserver` ).
I used postman 7.10 on Mac OS 10.14.
I saw that `Accept: gzip, deflate` was appearing in the temporary headers (screenshot 2 below) but it didn't have any negative effect on the api response.
I attached some screenshots below

verify email:
<img width="1132" alt="Screenshot 2019-11-05 at 10 58 35" src="https://user-images.githubusercontent.com/168152/68938160-12ceee80-079e-11ea-8a18-0bff2e83993e.png">

<img width="1141" alt="Screenshot 2019-11-05 at 11 32 00" src="https://user-images.githubusercontent.com/168152/68938116-f8951080-079d-11ea-858a-13f951ba8234.png">

verify registration:
<img width="1140" alt="Screenshot 2019-11-04 at 22 06 40" src="https://user-images.githubusercontent.com/168152/68938175-1cf0ed00-079e-11ea-88b3-e04153e84541.png">

Could you provide additional details:
* How is your tested API served (for instance, a WSGI app on gunicorn/uwsgi)?
* Is your API behind a proxy (for instance, nginx/haproxy)?
* Which version of postman on which OS are you using?

My current working hypothesis is that this is related to some misconfiguration which necessary may not be a Django-REST-Registration specific.

**Comment by beittenc** [comment] 2019-11-15 15:07
This is an awesome response! The API I'm writing is hosted on AWS Lambda, so not too much in front of it. When I submitted this ticket, I was running Postman 7.10 on Windows 10, however I've since gotten a new Macbook for work. When I retested this on v7.11 on MacOS, it worked fine. However, I tried again on v7.10 on Windows and the problem still exists.

**MacOS**
![image](https://user-images.githubusercontent.com/3846633/68953208-11de9280-0787-11ea-9d0e-98105bc759cb.png)

**Windows**
![image](https://user-images.githubusercontent.com/3846633/68953250-23c03580-0787-11ea-95dc-8ac3a1980cad.png)

So we may be into a fun realm of a Windows-specific issue, possibly with Postman's implementation. I'm not sure. Let me know if there's anything else I can provide.

**Comment by apragacz** [comment] 2019-11-17 21:07
@beittenc Thanks for the information!
It looks indeed that this issue seems to be Postman and/or OS related.
Could you please check whether this issue persists in version 7.11 on Windows (in other words, upgrade from 7.10 to 7.11)? If not, maybe they fixed the issue already.

If it still persist the we could try to dig in deeper but I'm wondering if it would be worth the time as it looks that Postman devs should solve this issue on it's own. In the meantime you could try other REST API clients like [Insomnia](https://insomnia.rest/).

**Comment by beittenc** [comment] 2019-11-21 15:13
Upgrading to Postman 7.11 doesn't fix the issue, unfortunately.

**Comment by apragacz** [comment] 2019-11-22 11:46
@beittenc thanks for the info. So it looks that there is a discrepancy between newest Postman version on both MacOS and Windows 10. So I will close this issue as I think it is not related to Django-REST-Registration. I'd suggest to [report a bug to Postman](https://github.com/postmanlabs/postman-app-support/issues/new?template=Bug_report.md) and link this issue as a reference.

**Closed by apragacz** 2019-11-22 11:46 UTC
Labels: type:bug

**Comment by Hikaon** [comment] 2019-12-03 15:31
I think this is unrelated to Postman. 
`'REGISTER_VERIFICATION_URL': 'https://mysite.example/verify-user/',` - this is suggested user verification url from docs, but signature generated with this url doesn't verify in `verify-email` URL, because its created by different Signers.
I suppose this is source of this confusion
