### ISSUE TITLE
Don't allow inactive users to log in

### ISSUE THREAD

**Issue by gcbirzan** [apragacz/django-rest-registration#52] opened 2019-05-13 10:54 UTC
If one is using `AllowAllUsersModelBackend` to display a different error for inactive users, these users will get a successful message for login, but their session won't work.

The fix is just adding 

    if not user.is_active:
        raise BadRequest('This account is inactive.')

to the login view.

**Comment by apragacz** [comment] 2019-05-13 11:13
I wasn't aware of this kind of backend.  But if someone replaces the backend with one that does not check the `is_active` field, then we should rather do the opposite, which is make the session work.

I'm surprised that the authenticated session does not work - IMO this looks like a bug in Django itself, but I'm not sure until I can reproduce it. Did you encounter this bug in your code? Or is it just theoretical discussion?

> ... but their session won't work.

What are the actual symptoms? Does `request.user` point to wrong user (unauthenticated one?) or is it something else?

I see that it may relate also to token authentication - I think that Django REST Framework checks that the user with given token is active during authentication. If that's true, then it could be a potential bug (or at least a inconsistency) in DRF.

**Comment by gcbirzan** [comment] 2019-05-13 11:38
> What are the actual symptoms? Does request.user point to wrong user (unauthenticated one?) or is it something else?

Anonymous user. The session authentication in DRF doesn't allow inactive users [here](https://github.com/encode/django-rest-framework/blob/a91e6a0e693f427a4559cee464aa240243f51d6a/rest_framework/authentication.py#L123).

All backends check for is_active when returning the user.

**Comment by apragacz** [comment] 2019-05-18 20:58
@gcbirzan 
So it looks that there is an inconsistency between Django authentication backends and DRF authentication classes. The former may accept inactive users as valid ones when authenticating, the former assumes that the user has to be active.

I would suggest to [file an issue in DRF](https://github.com/encode/django-rest-framework/issues/new). I don't see how we could fix that; your solution only masks the bigger problem. The only viable solution I see right now is to warn user via [Django system check](https://docs.djangoproject.com/en/dev/ref/checks/) that using `AllowAllUsersModelBackend` or `AllowAllUsersRemoteUserBackend ` will cause problems with DRF authentication classes. Do you think that is a fair solution? I'm open to other, better solutions, of course.

**Comment by apragacz** [comment] 2019-08-13 20:24
I added a check which will detect these backends in `AUTHENTICATION_BACKENDS`, so I'm closing this one. This should be released in next version (`0.5.1`).

**Closed by apragacz** 2019-08-13 20:24 UTC
