### ISSUE TITLE
Extend views

### ISSUE THREAD

**Issue by itzmanish** [apragacz/django-rest-registration#89] opened 2019-11-26 06:39 UTC
Is there any way to extend rest registration views and adding other functionallity?

**Comment by itzmanish** [comment] 2019-11-26 07:07
In DRR all views are function based so i don't know how i can extend it. Also to add simplejwt i need to modify login views. So It will be nice for everyone if DRR have generic views.

**Comment by apragacz** [comment] 2019-11-26 09:46
Hi @itzmanish ,
There is an issue #55 where is already a discussion going on about turning the function views into class based views. So I would route all related discussion there:

Therefore I'm closing this one as duplicate of  #55 .

BTW: I'm planning to address issue #84 in few days.

**Closed by apragacz** 2019-11-26 09:46 UTC
Labels: type:feature-request
